#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bindr
Version  : 0.1.1
Release  : 27
URL      : https://cran.r-project.org/src/contrib/bindr_0.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bindr_0.1.1.tar.gz
Summary  : Provides a simple interface for creating active bindings where the bound function accepts additional arguments.
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
BuildRequires : util-linux

%description
bindr [![Travis-CI Build Status](https://travis-ci.org/krlmlr/bindr.svg?branch=master)](https://travis-ci.org/krlmlr/bindr) [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/krlmlr/bindr?branch=master&svg=true)](https://ci.appveyor.com/project/krlmlr/bindr) [![Coverage Status](https://img.shields.io/codecov/c/github/krlmlr/bindr/master.svg)](https://codecov.io/github/krlmlr/bindr?branch=master) [![CRAN\_Status\_Badge](http://www.r-pkg.org/badges/version/bindr)](https://cran.r-project.org/package=bindr)
======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

%prep
%setup -q -c -n bindr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571802215

%install
export SOURCE_DATE_EPOCH=1571802215
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bindr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bindr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bindr
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc bindr || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bindr/DESCRIPTION
/usr/lib64/R/library/bindr/INDEX
/usr/lib64/R/library/bindr/LICENSE
/usr/lib64/R/library/bindr/Meta/Rd.rds
/usr/lib64/R/library/bindr/Meta/features.rds
/usr/lib64/R/library/bindr/Meta/hsearch.rds
/usr/lib64/R/library/bindr/Meta/links.rds
/usr/lib64/R/library/bindr/Meta/nsInfo.rds
/usr/lib64/R/library/bindr/Meta/package.rds
/usr/lib64/R/library/bindr/NAMESPACE
/usr/lib64/R/library/bindr/NEWS.md
/usr/lib64/R/library/bindr/R/bindr
/usr/lib64/R/library/bindr/R/bindr.rdb
/usr/lib64/R/library/bindr/R/bindr.rdx
/usr/lib64/R/library/bindr/help/AnIndex
/usr/lib64/R/library/bindr/help/aliases.rds
/usr/lib64/R/library/bindr/help/bindr.rdb
/usr/lib64/R/library/bindr/help/bindr.rdx
/usr/lib64/R/library/bindr/help/paths.rds
/usr/lib64/R/library/bindr/html/00Index.html
/usr/lib64/R/library/bindr/html/R.css
/usr/lib64/R/library/bindr/tests/testthat.R
/usr/lib64/R/library/bindr/tests/testthat/test-create.R
/usr/lib64/R/library/bindr/tests/testthat/test-error.R
/usr/lib64/R/library/bindr/tests/testthat/test-payload.R
/usr/lib64/R/library/bindr/tests/testthat/test-populate.R
